### ISSUE TITLE
$multiply fails

### ISSUE THREAD

**Issue by TheLudd** [kofrasa/mingo#184]
I have this code that runs an aggregation pipeline that should multiply value and probability on each document:

```
const { Aggregator } = require('mingo/aggregator')
const { useOperators, OperatorType } = require('mingo/core')
const { $project } = require('mingo/operators/pipeline')
const { $multiply } = require('mingo/operators/expression')

useOperators(OperatorType.PIPELINE, { $project })
useOperators(OperatorType.ACCUMULATOR, { $multiply })

const collection = [
  { value: 5000, probability: 0.5 },
  { value: 2000, probability: 0.7 },
]

const agg = new Aggregator([
  { $project: { product: { $multiply: [ '$value', '$probability' ] } } },
])

console.log(agg.run(collection))
```

I get this error when I run it: 
```
/tmp/mingo/node_modules/mingo/lazy.js:83
                throw e;
                ^

TypeError: Cannot read property 'reduce' of null
    at $multiply (/tmp/mingo/node_modules/mingo/operators/expression/arithmetic/multiply.js:15:17)
    at Object.computeValue (/tmp/mingo/node_modules/mingo/core.js:219:20)
    at _loop_1 (/tmp/mingo/node_modules/mingo/operators/pipeline/project.js:108:32)
    at processObject (/tmp/mingo/node_modules/mingo/operators/pipeline/project.js:155:9)
    at Object.func (/tmp/mingo/node_modules/mingo/operators/pipeline/project.js:36:16)
    at Iterator.__next (/tmp/mingo/node_modules/mingo/lazy.js:52:35)
    at Iterator.value (/tmp/mingo/node_modules/mingo/lazy.js:223:32)
    at Aggregator.run (/tmp/mingo/node_modules/mingo/aggregator.js:48:40)
    at Object.<anonymous> (/tmp/mingo/app.js:18:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
```

Is this a bug or some error in the usage?

**Comment by kofrasa** [comment]
The `$multiply`  operator belongs to type `OperatorType.EXPRESSION` but you are using it as an `OperatorType.ACCUMULATOR`.

**Comment by TheLudd** [comment]
Thank you, this made it work.
