### ISSUE TITLE
TypeError: CreateListFromArrayLike called on non-object

### ISSUE THREAD

**Issue by pubkey** [kofrasa/mingo#308]
When creating a custom build, I get the following errors when creating a query:
```
TypeError: CreateListFromArrayLike called on non-object
      at /home/user/workspace/rxdb/node_modules/mingo/lib/operators/_predicates.js:46:26
      at Query.processOperator (node_modules/mingo/lib/query.js:49:18)
      at Query.compile (node_modules/mingo/lib/query.js:38:26)
      at new Query (node_modules/mingo/lib/query.js:20:14)
      at getMingoQuery (src/rx-query-mingo.ts:66:12)
      at Object.getQueryMatcher (src/rx-storage-statics.ts:67:41)
      at Context.<anonymous> (test/unit/rx-storage-implementations.test.ts:1166:74)
```

Mingo version: 6.2.7

```ts
import { useOperators, OperatorType } from 'mingo/core';
import { Query } from 'mingo/query';
import type { MangoQuerySelector } from './types';
import { $project } from 'mingo/operators/pipeline/project';
import { $sort } from 'mingo/operators/pipeline/sort';
import { $and } from 'mingo/operators/expression/boolean/and';
import { $not } from 'mingo/operators/expression/boolean/not';
import { $or } from 'mingo/operators/expression/boolean/or';
import { $nor } from 'mingo/operators/query/logical/nor';
import { $eq } from 'mingo/operators/expression/comparison/eq';
import { $ne } from 'mingo/operators/expression/comparison/ne';
import { $gt } from 'mingo/operators/expression/comparison/gt';
import { $gte } from 'mingo/operators/expression/comparison/gte';
import { $lt } from 'mingo/operators/expression/comparison/lt';
import { $lte } from 'mingo/operators/expression/comparison/lte';
import { $regex } from 'mingo/operators/query/evaluation/regex';
import { $mod } from 'mingo/operators/query/evaluation/mod';
import { $elemMatch } from 'mingo/operators/projection/elemMatch';
import { $exists } from 'mingo/operators/query/element/exists';
import { $nin } from 'mingo/operators/query/comparison/nin';
import { $in } from 'mingo/operators/query/comparison/in';
import { $size } from 'mingo/operators/expression/array/size';
import { $type } from 'mingo/operators/expression/type/type';

let mingoInitDone = false;

export function getMingoQuery<RxDocType>(
    selector?: MangoQuerySelector<RxDocType>
) {
    if (!mingoInitDone) {

        useOperators(OperatorType.PIPELINE, {
            $sort,
            $project
        } as any);
        useOperators(OperatorType.QUERY, {
            $and,
            $eq,
            $elemMatch,
            $exists,
            $gt,
            $gte,
            $in,
            $lt,
            $lte,
            $ne,
            $nin,
            $mod,
            $nor,
            $not,
            $or,
            $regex,
            $size,
            $type,
        } as any);
        mingoInitDone = true;
    }
    return new Query(selector as any);
}


// the query is:

const query = {
                    selector: {
                        age: {
                            $gt: 10,
                            $ne: 50
                        }
                    },
                    sort: [
                        { _id: 'asc' }
                    ],
                    skip: 0
};

```

**Comment by kofrasa** [comment]
There is no method `CreateListFromArrayLike` in `mingo`. Is that defined somewhere in your library?

**Comment by pubkey** [comment]
The error comes from sending wrong data into Array.apply [see](https://stackoverflow.com/questions/41354099/getting-error-createlistfromarraylike-called-on-non-object-when-trying-to-use-a)

according to the stack trace, this comes from the `createExpressionOperator()` method of mingo:
![Screenshot from 2023-01-30 04-02-54](https://user-images.githubusercontent.com/8926560/215378747-5adfb985-f55e-460b-bd72-0eec8332e98e.png)

**Comment by pubkey** [comment]
Running this file on node.js reproduces the error. You need to have set `"type": "module"` in the package.json.

```js
import { useOperators, OperatorType } from 'mingo/core';
import { Query } from 'mingo/query';
import { $project } from 'mingo/operators/pipeline/project';
import { $sort } from 'mingo/operators/pipeline/sort';
import { $and } from 'mingo/operators/expression/boolean/and';
import { $not } from 'mingo/operators/expression/boolean/not';
import { $or } from 'mingo/operators/expression/boolean/or';
import { $nor } from 'mingo/operators/query/logical/nor';
import { $eq } from 'mingo/operators/expression/comparison/eq';
import { $ne } from 'mingo/operators/expression/comparison/ne';
import { $gt } from 'mingo/operators/expression/comparison/gt';
import { $gte } from 'mingo/operators/expression/comparison/gte';
import { $lt } from 'mingo/operators/expression/comparison/lt';
import { $lte } from 'mingo/operators/expression/comparison/lte';
import { $regex } from 'mingo/operators/query/evaluation/regex';
import { $mod } from 'mingo/operators/query/evaluation/mod';
import { $elemMatch } from 'mingo/operators/projection/elemMatch';
import { $exists } from 'mingo/operators/query/element/exists';
import { $nin } from 'mingo/operators/query/comparison/nin';
import { $in } from 'mingo/operators/query/comparison/in';
import { $size } from 'mingo/operators/expression/array/size';
import { $type } from 'mingo/operators/expression/type/type';

let mingoInitDone = false;

export function getMingoQuery(
    selector
) {
    if (!mingoInitDone) {

        useOperators(OperatorType.PIPELINE, {
            $sort,
            $project
        });
        useOperators(OperatorType.QUERY, {
            $and,
            $eq,
            $elemMatch,
            $exists,
            $gt,
            $gte,
            $in,
            $lt,
            $lte,
            $ne,
            $nin,
            $mod,
            $nor,
            $not,
            $or,
            $regex,
            $size,
            $type,
        });
        mingoInitDone = true;
    }
    return new Query(selector);
}

getMingoQuery({
    age: {
        $gt: 10,
        $ne: 50
    }
});
```

**Comment by pubkey** [comment]
Interestingly, running it on the browser returns a different but similar error:

```
TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function
	    at eval (webpack://rxdb/./node_modules/mingo/es/operators/_predicates.js?:54:16)
	    at Query.processOperator (webpack://rxdb/./node_modules/mingo/es/query.js?:54:20)
```

**Comment by kofrasa** [comment]
Something funny happening with the transpiler. It should be passing in `args` as an array and not a direct value.

**Comment by kofrasa** [comment]
It compiles `createQueryOperator` correctly

```js
function createQueryOperator(predicate) {
    return function (selector, value, options) {
        var opts = { unwrapArray: true };
        var depth = Math.max(1, selector.split(".").length - 1);
        return function (obj) {
            // value of field must be fully resolved.
            var lhs = (0, util_1.resolve)(obj, selector, opts);
            return predicate(lhs, value, __assign(__assign({}, options), { depth: depth }));
        };
    };
}
```

but for `createExpressionOperator`, it converts the call into an `apply` because I use the spread operator.

```js
function createExpressionOperator(predicate) {
    return function (obj, expr, options) {
        var args = (0, core_1.computeValue)(obj, expr, null, options);
        // console.log(args) --> returns the value 10.
        return predicate.apply(void 0, args);
    };
}
```

**Comment by kofrasa** [comment]
Ok, unfortunately the issue is due to weak type of enforcement of the operator function registered for their corresponding types.

Comparison expressions have different signatures when used to query documents directly via `Query` or when used in the aggregation pipeline.

You have registered the `expression` operator versions of the comparisons for the `query` operator type.

```
import { $eq } from 'mingo/operators/expression/comparison/eq';
import { $ne } from 'mingo/operators/expression/comparison/ne';
import { $gt } from 'mingo/operators/expression/comparison/gt';
import { $gte } from 'mingo/operators/expression/comparison/gte';
import { $lt } from 'mingo/operators/expression/comparison/lt';
import { $lte } from 'mingo/operators/expression/comparison/lte';
```

These should be

```
import { $eq } from 'mingo/operators/query/comparison/eq';
import { $ne } from 'mingo/operators/query/comparison/ne';
import { $gt } from 'mingo/operators/query/comparison/gt';
import { $gte } from 'mingo/operators/query/comparison/gte';
import { $lt } from 'mingo/operators/query/comparison/lt';
import { $lte } from 'mingo/operators/query/comparison/lte';
```

To avoid all of this hassle prefer to use the following as the initialization.

```
require("mingo")
```

It would only load the basic operators as defined [here](https://github.com/kofrasa/mingo/blob/199cf6fab4568e97224cbcdb1c2a3a3c545e7555/src/init/basic.ts)

**Comment by kofrasa** [comment]
The version of the comparison operators from the expression module must resolve to array as expected by the `predicate.apply` generated. The inner function of the `createExpressionOperator` should not even be evaluated in your example.

Unfortunately, these are some side effects of some design choices and a lack of good way to assert the type of functions. In a future version, I might consider wrapping operators in classes to get some instance based type checking.

Hope that helps.

**Comment by pubkey** [comment]
I am not able to use `require("mingo")` because that includes all operators in my javascript bundle.
Also importing all operators directly from `operators/query` will end up in adding all operators to the webpack bundle. like ```import {$and } from 'mingo/operators/query';```

I now changed all imports like you described and it works. Thank you for your time.

**Comment by kofrasa** [comment]
Using `require("mingo")` only adds the basic operators (comparison, booleans, and query) in your bundle. You can do also do `require("mingo/init/basic")` which gives the same effect and is more explicit.
