### ISSUE TITLE
$pull and $pullAll seem to be broken

### ISSUE THREAD

**Issue by vigan-abd** [kofrasa/mingo#413]
hi there, first of all thanks for this amazing library.

When testing these example it's returning error, not sure why but seems something to be broken during fix of issue https://github.com/kofrasa/mingo/issues/373
```
> const { updateObject } = require('mingo/updater')
undefined
> const obj = {
...     title: "Tobi",
...     author: "Brian",
...     date: "2023-09-30T15:45:44.097Z",
...     owners: ["owner1", "owner2"],
...     comments: [
...         {
...             _id: "comment1",
...             date: null,
...             body: "been there",
...         },
...         {
...             _id: "comment2",
...             date: null,
...             body: "done that",
...         },
...     ],
...     _id: "651842a8b50c196f074197ce",
... }
undefined
> updateObject(obj, {
...     $pull: { "comments._id": { $in: ["comment1"] } },
... });
Uncaught Error: unknown operator $in
    at Query.processOperator (/.../node_modules/mingo/dist/cjs/query.js:46:19)
    at Query.compile (/.../node_modules/mingo/dist/cjs/query.js:35:26)
    at new Query (/.../node_modules/mingo/dist/cjs/query.js:19:14)
    at /.../node_modules/mingo/dist/cjs/operators/update/pull.js:12:23
    at walkExpression (/.../node_modules/mingo/dist/cjs/operators/update/_internal.js:95:17)
    at $pull (/.../node_modules/mingo/dist/cjs/operators/update/pull.js:9:43)
    at /.../node_modules/mingo/dist/cjs/updater.js:60:16
> 

> updateObject(obj, {
...      $pullAll: { "comments._id": ["comment1"] },
... });
Uncaught Error: unknown operator $in
    at Query.processOperator (/.../node_modules/mingo/dist/cjs/query.js:46:19)
    at Query.compile (/.../node_modules/mingo/dist/cjs/query.js:35:26)
    at new Query (/.../node_modules/mingo/dist/cjs/query.js:19:14)
    at /.../node_modules/mingo/dist/cjs/operators/update/pull.js:12:23
    at walkExpression (/.../node_modules/mingo/dist/cjs/operators/update/_internal.js:95:17)
    at $pull (/.../node_modules/mingo/dist/cjs/operators/update/pull.js:9:43)
    at $pullAll (/.../node_modules/mingo/dist/cjs/operators/update/pullAll.js:11:29)
    at /.../node_modules/mingo/dist/cjs/updater.js:60:16
```

**Comment by kofrasa** [comment]
Hi @vigan-abd, thanks for reporting this issue. So the behaviour is not "broken" per se but rather it is a side of how operator loading works in the library which is by design to support tree-shaking for web installations. All query operators used in the update expression should be explicitly loaded. 

That said, it might be better to load the basic query operators directly in the update context as done [here](https://github.com/kofrasa/mingo/blob/main/src/init/basic.ts#L22). This would make the basic query operators available.

You can add the snippet below to your imports to fix it. 

```js
const { OperatorType, useOperators } = require("mingo/core");
const queryOperators = require("mingo/operators/query");
const { updateObject } = require('mingo/updater')

useOperators(OperatorType.QUERY, queryOperators);
``` 

A simpler option to just use the side effect import below but that loads a few more unnecessary operators.

```js
require("mingo/init/basic") // loads minimal operators (including "$in") required for most common use-cases.
const { updateObject } = require('mingo/updater')

// do stuff here.
```

Will keep this issue open for now while I ponder a better way to handle this.

**Comment by kofrasa** [comment]
Running your example with the operators loaded is a no-op. For an actual MongoDB database it seems to be disallowed with the error below. See example here https://mongoplayground.net/p/JRwrWHT6pN3.

```
fail to run update: write exception: write errors: [Cannot use the part (_id) of (comments._id) to traverse the element ({comments: [ { date: null, body: "been there", _id: "comment1" }, { _id: "comment2", date: null, body: "done that" } ]})]
```

**Comment by vigan-abd** [comment]
sorry, it should have been like this
```
db.collection.update({},
{
  $pull: {
    comments: {
      _id: {
        $in: [
          "comment1"
        ]
      }
    }
  }
},
{
  "upsert": false
})
```

**Comment by kofrasa** [comment]
That works as expected.
