### ISSUE TITLE
$concatArrays should not limit to 2 elements

### ISSUE THREAD

**Issue by saadtazi** [kofrasa/mingo#64]
Hello,

According to [the mongodb documentation](https://docs.mongodb.com/manual/reference/operator/aggregation/concatArrays/index.html), $concatArrys operator allows multiple elements.

But mingo only allows 2 elements:
https://github.com/kofrasa/mingo/blob/34c5ac7ba9a9409610eb72cc5ae19306a429c08b/lib/operators/expression/array.js#L71

repro step:

```
const data = [{professionalTags: ['tag1', 'tag2'], personalTags: ['tag2'], publicationTags: ['tag2']}];
mingo.aggregate(data, [
  { $project: {
    tags: {$concatArrays: ['$professionalTags', '$personalTags', '$publicationTags'] }
  }}
]);
```

this throws an exception: 

```
$concatArrays expression must resolve to an array of 2 elements

      at err (node_modules/mingo/dist/mingo.js:140:9)
      at assert (node_modules/mingo/dist/mingo.js:40:26)
      at Object.$concatArrays (node_modules/mingo/dist/mingo.js:2438:5)
      at computeValue (node_modules/mingo/dist/mingo.js:3805:38)
      at node_modules/mingo/dist/mingo.js:3852:23
      at each (node_modules/mingo/dist/mingo.js:182:16)
      at computeValue (node_modules/mingo/dist/mingo.js:3851:7)
      at node_modules/mingo/dist/mingo.js:950:19
      at each (node_modules/mingo/dist/mingo.js:177:14)
      at node_modules/mingo/dist/mingo.js:914:5
      at each (node_modules/mingo/dist/mingo.js:177:14)
      at Object.$project (node_modules/mingo/dist/mingo.js:904:3)
      at node_modules/mingo/dist/mingo.js:1248:48
      at each (node_modules/mingo/dist/mingo.js:177:14)
      at Aggregator.run (node_modules/mingo/dist/mingo.js:1241:9)
      at Object.aggregate (node_modules/mingo/dist/mingo.js:1267:35)
      at Object.<anonymous>.exports.getAllSkills.elementals (src/selectors/index.js:10:26)
      at Object.it (src/selectors/__tests__/index.test.js:7:38)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

Note that removing one element (`$publicationTags` for example) doesn't throw.

**Comment by kofrasa** [comment]
Thanks for reporting this @saadtazi.  

I am not sure why I bound it to two arrays.  Please feel free to submit a PR.

Thanks.

**Comment by saadtazi** [comment]
I'll give it a try this week-end.

**Comment by kofrasa** [comment]
fixed https://github.com/kofrasa/mingo/commit/8bfb08366e259e5c4140f7d292fff3555fc046e0
